### ISSUE TITLE
Doc inconsistency 

### ISSUE THREAD

**Issue by RodenLuo** [RBVI/ChimeraX-Bundle-Template#1]
I come to this repo from https://www.cgl.ucsf.edu/chimerax/docs/devel/writing_bundles.html#bundle-sample-code. It is documented that "Because the sample code includes C++ source code." But there is no C++ code (_sample_pyapi.cpp and _sample_pybind11.cpp as mentioned) in this repo. A few other listed files in the doc do not exist, either.

**Comment by RodenLuo** [comment]
Not a big deal. But somewhat confusing. The same holds for https://github.com/RBVI/ChimeraX-Bundle-Template-TOML.

**Comment by tomgoddard** [comment]
Thanks for pointing out the missing files in the bundle documentation.  Here are the missing .cpp files

    https://github.com/RBVI/ChimeraX/tree/develop/src/examples/sample/src

and I have made a ChimeraX bug report so the missing links to the example files will be fixed in the documentation.

   https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/15001

**Comment by RodenLuo** [comment]
Looks like it is solved now. Thanks! 👍
